### ISSUE TITLE
로그인할때 오류응답코드 세부화필요

### ISSUE THREAD

**Issue by helloimda** [ehdtjr/hoseo_meet#1]
로그인 실패시 현재 비번이 틀렸을때 혹은 정상적인 비밀번호 기입후 이메일인증을 안했을때의 오류 응답코드 400을 띄우며
{
  "detail": "LOGIN_BAD_CREDENTIALS"
}
를 출력함 사용자에게 알맞은 오류 알림을 위해 세부화가 필요해보임

**Comment by 11kkw** [comment]
이슈 해결: 로그인 실패 시 세부 오류 응답 코드 수정
로그인 시 비밀번호 오류와 이메일 인증 미완료 상태에 대한 응답을 세분화하였습니다.

수정 사항:

- 이메일 인증 미완료 시: 이제 403 Forbidden 응답 코드가 반환되며, {"detail": "이메일 인증이 필요합니다. 이메일을 확인해주세요."} 메시지가 표시됩니다.

- 비밀번호 오류 시: 잘못된 비밀번호 입력 시 400 Bad Request 응답 코드와 함께 {"detail": "LOGIN_BAD_CREDENTIALS"} 메시지가 반환됩니다.

해당 시나리오에 대한 테스트도 완료하였습니다.

참조 커밋: dfcfdf5c329fc9fd2b875f3c0a5f6ef59377076b

**Comment by 11kkw** [comment]
이슈 해결: 로그인 실패 시 세부 오류 응답 코드 수정
로그인 시 비밀번호 오류와 이메일 인증 미완료 상태에 대한 응답을 세분화하였습니다.

수정 사항:

- 이메일 인증 미완료 시: 이제 403 Forbidden 응답 코드가 반환되며, {"detail": "이메일 인증이 필요합니다. 이메일을 확인해주세요."} 메시지가 표시됩니다.

- 비밀번호 오류 시: 잘못된 비밀번호 입력 시 400 Bad Request 응답 코드와 함께 {"detail": "LOGIN_BAD_CREDENTIALS"} 메시지가 반환됩니다.

해당 시나리오에 대한 테스트도 완료하였습니다.

참조 커밋: dfcfdf5c329fc9fd2b875f3c0a5f6ef59377076b
