### ISSUE TITLE
이메일 인증 ip오류

### ISSUE THREAD

**Issue by helloimda** [ehdtjr/hoseo_meet#5]
http://10.0.128.76:8000/api/v1/auth/verify-email?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2IiwiYXVkIjpbImZhc3RhcGktdXNlcnM6YXV0aCJdLCJleHAiOjE3Mjk0MjYwNDd9.83SUlpz5DGW04RmpEXfcXU8lynu7d0eEXo1sVYrkKbk

도메인서버가 아닌 로컬ip로 구현되어있음 도메인주소에 맞게 수정필요

**Comment by 11kkw** [comment]
해당 오류는 서버가 env 설정을 할때 domain에 ec2 ip를 써서 해당 오류가 발생한것 같습니다 뒤에 포트가 : 8000이 강제로 붙는 에러가 있는데 해당 오류를 수정하였습니다
